import { useEffect, useState } from "react";
import { BriefcaseBusiness, CheckSquare2, CircleDollarSign, FilePlus2, Goal, UserPlus } from "lucide-react";
import { hasPermission } from "../lib/permissions";
import { useAuth } from "../services/auth";
import { useWorkspace } from "../services/workspace";
import type { QuickAddType, Role } from "../types";
import { Button, Modal, SelectInput, TextArea, TextInput, useToast } from "./ui";

const labels: Record<QuickAddType, string> = { client: "Add client", user: "Add team member", project: "Create project", task: "Create task", approval: "Request approval", finance: "Add finance record", goal: "Create goal" };
const icons = { client: BriefcaseBusiness, user: UserPlus, project: FilePlus2, task: CheckSquare2, approval: CheckSquare2, finance: CircleDollarSign, goal: Goal };

const dateIn = (days: number) => { const date = new Date(); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10); };

export function QuickAddModal({ open, onClose, initialType }: { open: boolean; onClose: () => void; initialType?: QuickAddType }) {
  const { user } = useAuth();
  const { data, addClient, addUser, addProject, addTask, addApproval, addFinance, addGoal } = useWorkspace();
  const { notify } = useToast();
  const [type, setType] = useState<QuickAddType | null>(initialType ?? null);
  const [submitting, setSubmitting] = useState(false);
  const [form, setForm] = useState<Record<string, string>>({});

  useEffect(() => {
    if (open) { setType(initialType ?? null); setForm({}); }
  }, [initialType, open]);

  if (!user) return null;
  const available: QuickAddType[] = [
    ...(hasPermission(user, "clients:write") ? ["client" as const] : []),
    ...(hasPermission(user, "people:write") ? ["user" as const] : []),
    ...(hasPermission(user, "projects:write") ? ["project" as const] : []),
    ...(hasPermission(user, "tasks:write") ? ["task" as const] : []),
    ...(hasPermission(user, "approvals:write") ? ["approval" as const] : []),
    ...(hasPermission(user, "finance:write") ? ["finance" as const] : []),
    ...(user.role === "director" || user.role === "manager" ? ["goal" as const] : []),
  ];
  const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const required = (keys: string[]) => keys.every((key) => form[key]?.trim());

  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!type) return;
    let valid = true;
    if (type === "client") valid = required(["name", "company", "email"]);
    if (type === "user") valid = required(["name", "email", "title", "role"]);
    if (type === "project") valid = required(["name", "ownerId", "dueDate"]);
    if (type === "task") valid = required(["title", "dueDate"]);
    if (type === "approval") valid = required(["title", "approvalType"]);
    if (type === "finance") valid = required(["title", "amount", "financeType"]);
    if (type === "goal") valid = required(["title", "scope", "dueDate"]);
    if (!valid) { notify("Please complete the required fields.", "error"); return; }
    setSubmitting(true);
    try {
      if (type === "client") await addClient({ name: form.name, company: form.company, email: form.email, phone: form.phone ?? "", industry: form.industry ?? "Creative services", city: form.city ?? "", country: form.country ?? "India", status: (form.status as "Active" | "Onboarding" | "At risk" | "Inactive") || "Onboarding", paymentStatus: (form.paymentStatus as "Paid" | "Due soon" | "Overdue" | "Not set") || "Not set", managerId: form.managerId || undefined, budget: Number(form.budget) || 0, portalAccess: form.portalAccess === "true", notes: form.notes ?? "" });
      if (type === "user") await addUser({ name: form.name, email: form.email, title: form.title, role: form.role as Role, departmentId: form.departmentId || undefined, teamId: form.teamId || undefined, managerId: form.managerId || undefined, teamLeadId: form.teamLeadId || undefined });
      if (type === "project") await addProject({ name: form.name, clientId: form.clientId || undefined, ownerId: form.ownerId || user.id, managerId: form.managerId || undefined, teamLeadId: form.teamLeadId || undefined, priority: (form.priority as "Low" | "Medium" | "High" | "Urgent") || "Medium", dueDate: form.dueDate, budget: Number(form.budget) || 0, description: form.description ?? "" });
      if (type === "task") await addTask({ title: form.title, projectId: form.projectId || undefined, assigneeId: form.assigneeId || undefined, priority: (form.priority as "Low" | "Medium" | "High" | "Urgent") || "Medium", dueDate: form.dueDate || dateIn(7), description: form.description ?? "" });
      if (type === "approval") await addApproval({ title: form.title, type: (form.approvalType as "Deliverable" | "Leave" | "Finance" | "Change request") || "Deliverable", projectId: form.projectId || undefined, reviewerId: form.reviewerId || undefined, amount: form.amount ? Number(form.amount) : undefined, comment: form.comment ?? "" });
      if (type === "finance") await addFinance({ title: form.title, type: (form.financeType as "Budget" | "Expense" | "Invoice" | "Payment") || "Expense", clientId: form.clientId || undefined, projectId: form.projectId || undefined, amount: Number(form.amount) || 0, status: (form.financeStatus as "Draft" | "Pending" | "Approved" | "Paid" | "Overdue") || "Draft", dueDate: form.dueDate || undefined });
      if (type === "goal") await addGoal({ title: form.title, scope: (form.scope as "Organization" | "Department" | "Team" | "Project" | "Personal") || "Organization", ownerId: form.ownerId || user.id, progress: Number(form.progress) || 0, dueDate: form.dueDate || dateIn(30), status: (form.goalStatus as "On track" | "At risk" | "Complete") || "On track" });
      notify(`${labels[type]} saved successfully.`, "success");
      onClose();
    } catch (error) {
      notify(error instanceof Error ? error.message : "The record could not be saved.", "error");
    } finally { setSubmitting(false); }
  };

  const renderForm = () => {
    if (type === "client") return <div className="form-grid"><TextInput label="Client name *" placeholder="Sana Kapoor" value={form.name ?? ""} onChange={(event) => set("name", event.target.value)} /><TextInput label="Company *" placeholder="Aster Labs" value={form.company ?? ""} onChange={(event) => set("company", event.target.value)} /><TextInput label="Email *" type="email" placeholder="hello@company.com" value={form.email ?? ""} onChange={(event) => set("email", event.target.value)} /><TextInput label="Phone" placeholder="+91 98765 00000" value={form.phone ?? ""} onChange={(event) => set("phone", event.target.value)} /><TextInput label="Industry" placeholder="SaaS" value={form.industry ?? ""} onChange={(event) => set("industry", event.target.value)} /><TextInput label="City" placeholder="Bengaluru" value={form.city ?? ""} onChange={(event) => set("city", event.target.value)} /><SelectInput label="Status" value={form.status ?? "Onboarding"} onChange={(event) => set("status", event.target.value)}><option>Onboarding</option><option>Active</option><option>At risk</option><option>Inactive</option></SelectInput><SelectInput label="Payment status" value={form.paymentStatus ?? "Not set"} onChange={(event) => set("paymentStatus", event.target.value)}><option>Not set</option><option>Paid</option><option>Due soon</option><option>Overdue</option></SelectInput><TextInput label="Budget (₹)" type="number" min="0" placeholder="100000" value={form.budget ?? ""} onChange={(event) => set("budget", event.target.value)} /><SelectInput label="Assigned manager" value={form.managerId ?? ""} onChange={(event) => set("managerId", event.target.value)}><option value="">Unassigned</option>{data.users.filter((candidate) => candidate.role === "manager").map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</SelectInput><TextArea label="Notes" className="field-span-2" placeholder="Context the team should know" value={form.notes ?? ""} onChange={(event) => set("notes", event.target.value)} /></div>;
    if (type === "user") return <div className="form-grid"><TextInput label="Full name *" placeholder="A new teammate" value={form.name ?? ""} onChange={(event) => set("name", event.target.value)} /><TextInput label="Email *" type="email" placeholder="name@company.com" value={form.email ?? ""} onChange={(event) => set("email", event.target.value)} /><TextInput label="Title *" placeholder="Product Designer" value={form.title ?? ""} onChange={(event) => set("title", event.target.value)} /><SelectInput label="Role *" value={form.role ?? "employee"} onChange={(event) => set("role", event.target.value)}><option value="employee">Employee</option><option value="team_leader">Team Lead</option>{user.role === "director" ? <option value="manager">Manager</option> : null}</SelectInput><SelectInput label="Department" value={form.departmentId ?? ""} onChange={(event) => set("departmentId", event.target.value)}><option value="">Unassigned</option>{data.departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</SelectInput><SelectInput label="Team" value={form.teamId ?? ""} onChange={(event) => set("teamId", event.target.value)}><option value="">Unassigned</option>{data.teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</SelectInput><SelectInput label="Reporting manager" value={form.managerId ?? ""} onChange={(event) => set("managerId", event.target.value)}><option value="">Unassigned</option>{data.users.filter((candidate) => candidate.role === "manager").map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</SelectInput></div>;
    if (type === "project") return <div className="form-grid"><TextInput label="Project name *" placeholder="New client project" value={form.name ?? ""} onChange={(event) => set("name", event.target.value)} /><SelectInput label="Client" value={form.clientId ?? ""} onChange={(event) => set("clientId", event.target.value)}><option value="">Internal project</option>{data.clients.map((client) => <option key={client.id} value={client.id}>{client.company}</option>)}</SelectInput><SelectInput label="Owner *" value={form.ownerId ?? user.id} onChange={(event) => set("ownerId", event.target.value)}>{data.users.filter((candidate) => candidate.role !== "client").map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</SelectInput><SelectInput label="Manager" value={form.managerId ?? ""} onChange={(event) => set("managerId", event.target.value)}><option value="">Unassigned</option>{data.users.filter((candidate) => candidate.role === "manager").map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</SelectInput><SelectInput label="Priority" value={form.priority ?? "Medium"} onChange={(event) => set("priority", event.target.value)}><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></SelectInput><TextInput label="Due date *" type="date" value={form.dueDate ?? dateIn(14)} onChange={(event) => set("dueDate", event.target.value)} /><TextInput label="Budget (₹)" type="number" min="0" value={form.budget ?? ""} onChange={(event) => set("budget", event.target.value)} /><TextArea label="Description" className="field-span-2" placeholder="What outcome should this project create?" value={form.description ?? ""} onChange={(event) => set("description", event.target.value)} /></div>;
    if (type === "task") return <div className="form-grid"><TextInput label="Task title *" placeholder="What needs to happen?" value={form.title ?? ""} onChange={(event) => set("title", event.target.value)} /><SelectInput label="Project" value={form.projectId ?? ""} onChange={(event) => set("projectId", event.target.value)}><option value="">No project</option>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</SelectInput><SelectInput label="Assignee" value={form.assigneeId ?? ""} onChange={(event) => set("assigneeId", event.target.value)}><option value="">Unassigned</option>{data.users.filter((candidate) => candidate.role !== "client").map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</SelectInput><SelectInput label="Priority" value={form.priority ?? "Medium"} onChange={(event) => set("priority", event.target.value)}><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></SelectInput><TextInput label="Due date *" type="date" value={form.dueDate ?? dateIn(7)} onChange={(event) => set("dueDate", event.target.value)} /><TextArea label="Description" className="field-span-2" placeholder="Add useful context for the person doing the work" value={form.description ?? ""} onChange={(event) => set("description", event.target.value)} /></div>;
    if (type === "approval") return <div className="form-grid"><TextInput label="Approval title *" placeholder="Aster launch hero direction" value={form.title ?? ""} onChange={(event) => set("title", event.target.value)} /><SelectInput label="Type *" value={form.approvalType ?? "Deliverable"} onChange={(event) => set("approvalType", event.target.value)}><option>Deliverable</option><option>Leave</option><option>Finance</option><option>Change request</option></SelectInput><SelectInput label="Project" value={form.projectId ?? ""} onChange={(event) => set("projectId", event.target.value)}><option value="">No project</option>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</SelectInput><SelectInput label="Reviewer" value={form.reviewerId ?? ""} onChange={(event) => set("reviewerId", event.target.value)}><option value="">Choose reviewer</option>{data.users.filter((candidate) => candidate.id !== user.id && candidate.role !== "employee").map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</SelectInput><TextInput label="Amount (₹)" type="number" min="0" value={form.amount ?? ""} onChange={(event) => set("amount", event.target.value)} /><TextArea label="Comment" className="field-span-2" placeholder="Give the reviewer enough context" value={form.comment ?? ""} onChange={(event) => set("comment", event.target.value)} /></div>;
    if (type === "finance") return <div className="form-grid"><TextInput label="Record title *" placeholder="Invoice or expense name" value={form.title ?? ""} onChange={(event) => set("title", event.target.value)} /><SelectInput label="Type *" value={form.financeType ?? "Expense"} onChange={(event) => set("financeType", event.target.value)}><option>Budget</option><option>Expense</option><option>Invoice</option><option>Payment</option></SelectInput><TextInput label="Amount *" type="number" min="0" value={form.amount ?? ""} onChange={(event) => set("amount", event.target.value)} /><SelectInput label="Status" value={form.financeStatus ?? "Draft"} onChange={(event) => set("financeStatus", event.target.value)}><option>Draft</option><option>Pending</option><option>Approved</option><option>Paid</option><option>Overdue</option></SelectInput><SelectInput label="Client" value={form.clientId ?? ""} onChange={(event) => set("clientId", event.target.value)}><option value="">No client</option>{data.clients.map((client) => <option key={client.id} value={client.id}>{client.company}</option>)}</SelectInput><SelectInput label="Project" value={form.projectId ?? ""} onChange={(event) => set("projectId", event.target.value)}><option value="">No project</option>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</SelectInput><TextInput label="Due date" type="date" value={form.dueDate ?? ""} onChange={(event) => set("dueDate", event.target.value)} /></div>;
    return <div className="form-grid"><TextInput label="Goal title *" placeholder="Improve on-time delivery" value={form.title ?? ""} onChange={(event) => set("title", event.target.value)} /><SelectInput label="Scope *" value={form.scope ?? "Organization"} onChange={(event) => set("scope", event.target.value)}><option>Organization</option><option>Department</option><option>Team</option><option>Project</option><option>Personal</option></SelectInput><SelectInput label="Owner" value={form.ownerId ?? user.id} onChange={(event) => set("ownerId", event.target.value)}>{data.users.filter((candidate) => candidate.role !== "client").map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</SelectInput><TextInput label="Due date *" type="date" value={form.dueDate ?? dateIn(30)} onChange={(event) => set("dueDate", event.target.value)} /><TextInput label="Starting progress (%)" type="number" min="0" max="100" value={form.progress ?? "0"} onChange={(event) => set("progress", event.target.value)} /><SelectInput label="Health" value={form.goalStatus ?? "On track"} onChange={(event) => set("goalStatus", event.target.value)}><option>On track</option><option>At risk</option><option>Complete</option></SelectInput></div>;
  };

  return <Modal open={open} onClose={onClose} title={type ? labels[type] : "Quick add"} subtitle={type ? "A real workspace record with validation and activity history." : "Choose an action to get useful work moving."} wide={Boolean(type)} footer={type ? <><Button variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" form="quick-add-form" loading={submitting}>Save {labels[type].replace(/^(Add|Create|Request) /, "")}</Button></> : null}>{type ? <form id="quick-add-form" onSubmit={submit}>{renderForm()}</form> : <div className="quick-actions">{available.map((item) => { const Icon = icons[item]; return <button className="quick-action" type="button" key={item} onClick={() => setType(item)}><span className="quick-action-icon"><Icon size={19} /></span><span><strong>{labels[item]}</strong><small>{item === "task" ? "Capture a next action" : item === "client" ? "Start a new account" : item === "project" ? "Create a clear outcome" : item === "user" ? "Add a scoped profile" : "Keep the workflow moving"}</small></span></button>; })}</div>}</Modal>;
}
